<?php

declare(strict_types=1);

return [

    'dashboard_message_1' => 'La piattaforma Spectrum è un potente strumento per la gestione e l\'analisi dei set di dati sul microbioma nel contesto della salute delle piante. Offre un\'interfaccia facile da usare per caricare, condividere e analizzare i set di dati, oltre a funzioni avanzate per la visualizzazione dei dati e la collaborazione.',
    'dashboard_message_2' => 'Per iniziare, è possibile caricare i propri set di dati, esplorare quelli condivisi o controllare le ultime notifiche. Se avete domande o bisogno di assistenza, non esitate a contattare il nostro team di supporto.',
    'dashboard_message_3' => 'Ci auguriamo che la Spectrum Data Platform vi sia utile per le vostre esigenze di ricerca e analisi dei dati!',

    'explore_introduction' => 'Qui è possibile esplorare il contenuto del dataset :name. È possibile visualizzare i dati utilizzando diverse analisi mirate ai microbiomi vegetali. Fare clic sui link a sinistra per navigare tra le diverse sezioni.',

    'alpha_diversity_description_1' => 'La figura mostra i boxplot della alpha diversity che illustrano la distribuzione della diversità microbica all\'interno dei singoli campioni attraverso diversi gruppi o condizioni. Il grafico visualizza misure statistiche chiave: la linea centrale rappresenta il valore mediano di diversità, mentre i confini della scatola indicano il primo e terzo quartile (25° e 75° percentile). I baffi si estendono per mostrare l\'intervallo dei valori tipici, e qualsiasi punto oltre i baffi rappresenta valori anomali con diversità insolitamente alta o bassa.',
    'alpha_diversity_description_2' => 'Confrontando i boxplot tra diversi gruppi, è possibile identificare pattern nella diversità microbica. I gruppi con valori mediani più alti hanno una diversità media maggiore, mentre l\'altezza di ogni scatola indica la variabilità all\'interno di quel gruppo. Scatole che si sovrappongono suggeriscono livelli di diversità simili tra i gruppi, mentre scatole che non si sovrappongono possono indicare differenze significative nella ricchezza e uniformità delle comunità microbiche.',

    'beta_diversity_description_1' => 'La figura mostra un grafico di Analisi delle Coordinate Principali (PCoA) della beta diversity. Visualizza le differenze nella composizione delle comunità microbiche tra i campioni. Ogni punto sul grafico rappresenta un singolo campione, e la distanza tra i punti riflette quanto simili o diverse sono le comunità microbiche. I campioni che si raggruppano insieme (appaiono vicini tra loro) hanno composizioni microbiche simili, mentre i campioni che sono distanti hanno strutture comunitarie molto diverse.',
    'beta_diversity_description_2' => 'Il grafico visualizza i dati in due dimensioni, con ogni asse che mostra la percentuale di variazione spiegata da quella particolare coordinata. Quando i campioni si raggruppano in cluster distinti, questo spesso indica che condividono condizioni ambientali simili, trattamenti, o altri fattori che influenzano l\'assemblaggio delle comunità microbiche. I valori percentuali su ogni asse aiutano a comprendere quanto della variazione totale nel dataset è catturata dalla visualizzazione — percentuali più elevate indicano che più differenze comunitarie sono rappresentate nel grafico.',

    'diff_abundance_top_significant_description' => 'Il grafico mostra i primi :n batteri in ordine di significatività statistica &mdash; dal più significativo al meno significativo &mdash; che mostrano un cambiamento di abbondanza tra :condition1 e :condition2. La lunghezza di ogni barra è proporzionale alla magnitudo del cambiamento osservato. Il colore indica il tipo di cambiamento. Una barra di colore rosso rappresenta i batteri con una abbondanza più elevata in :condition1 rispetto a :condition2. Una barra di colore blu rappresenta i batteri con una abbondanza ridotta in :condition1 rispetto a :condition2. Accanto ad ogni barra possono essere presenti dei simboli, che codificano la significatività statistica: *** altissima significatività, ** alta significatività, * significatività media, . significatività bassa.',
    'diff_abundance_top_fold_change_description' => 'Il grafico mostra i primi :n batteri in ordine di cambiamento di abbondanza &mdash; dal più alterato al meno alterato &mdash; tra :condition1 e :condition2. La lunghezza di ogni barra è proporzionale alla magnitudo del cambiamento osservato. Il colore indica il tipo di cambiamento. Una barra di colore rosso rappresenta i batteri con una abbondanza più elevata in :condition1 rispetto a :condition2. Una barra di colore blu rappresenta i batteri con una abbondanza ridotta in :condition1 rispetto a :condition2. Accanto ad ogni barra possono essere presenti dei simboli, che codificano la significatività statistica: *** altissima significatività, ** alta significatività, * significatività media, . significatività bassa.',
    'diff_abundance_top_frequent_description' => 'Il grafico mostra i primi :n batteri in ordine di frequenza &mdash; dal più frequente al meno frequente &mdash; che mostrano un cambiamento di abbondanza tra :condition1 e :condition2. La lunghezza di ogni barra è proporzionale alla magnitudo del cambiamento osservato. Il colore indica il tipo di cambiamento. Una barra di colore rosso rappresenta i batteri con una abbondanza più elevata in :condition1 rispetto a :condition2. Una barra di colore blu rappresenta i batteri con una abbondanza ridotta in :condition1 rispetto a :condition2. Accanto ad ogni barra possono essere presenti dei simboli, che codificano la significatività statistica: *** altissima significatività, ** alta significatività, * significatività media, . significatività bassa.',

    'functional_top_significant_description' => 'Il grafico mostra le prime :n feature in ordine di significatività statistica &mdash; dalla più significativa alla meno significativa &mdash; che mostrano un cambiamento di abbondanza tra :condition1 e :condition2. La lunghezza di ogni barra è proporzionale alla magnitudo del cambiamento osservato. Il colore indica il tipo di cambiamento. Una barra di colore rosso rappresenta le feature con una abbondanza più elevata in :condition1 rispetto a :condition2. Una barra di colore blu rappresenta le feature con una abbondanza ridotta in :condition1 rispetto a :condition2. Accanto ad ogni barra possono essere presenti dei simboli, che codificano la significatività statistica: *** altissima significatività, ** alta significatività, * significatività media, . significatività bassa.',
    'functional_top_fold_change_description' => 'Il grafico mostra le prime :n feature in ordine di cambiamento di abbondanza &mdash; dalla più alterata alla meno alterata &mdash; tra :condition1 e :condition2. La lunghezza di ogni barra è proporzionale alla magnitudo del cambiamento osservato. Il colore indica il tipo di cambiamento. Una barra di colore rosso rappresenta le feature con una abbondanza più elevata in :condition1 rispetto a :condition2. Una barra di colore blu rappresenta le feature con una abbondanza ridotta in :condition1 rispetto a :condition2. Accanto ad ogni barra possono essere presenti dei simboli, che codificano la significatività statistica: *** altissima significatività, ** alta significatività, * significatività media, . significatività bassa.',
    'functional_top_frequent_description' => 'Il grafico mostra le prime :n feature in ordine di frequenza &mdash; dalla più frequente alla meno frequente &mdash; che mostrano un cambiamento di abbondanza tra :condition1 e :condition2. La lunghezza di ogni barra è proporzionale alla magnitudo del cambiamento osservato. Il colore indica il tipo di cambiamento. Una barra di colore rosso rappresenta le feature con una abbondanza più elevata in :condition1 rispetto a :condition2. Una barra di colore blu rappresenta le feature con una abbondanza ridotta in :condition1 rispetto a :condition2. Accanto ad ogni barra possono essere presenti dei simboli, che codificano la significatività statistica: *** altissima significatività, ** alta significatività, * significatività media, . significatività bassa.',
];
