<?php

declare(strict_types=1);

return [

    'dashboard_message_1' => 'The Spectrum Data Platform is a powerful tool for managing and analyzing microbiome datasets in the context of plant health. It provides a user-friendly interface for uploading, sharing, and analyzing datasets, along with advanced features for data visualization and collaboration.',
    'dashboard_message_2' => 'To get started, you can upload your own datasets, explore shared datasets, or check out the latest notifications. If you have any questions or need assistance, feel free to reach out to our support team.',
    'dashboard_message_3' => 'We hope you find the Spectrum Data Platform useful for your research and data analysis needs!',

    'explore_introduction' => 'Here you can explore the content of the dataset :name. You can view the data using several analysis targeted to plant microbiomes. Click on the links on the left to navigate to the different sections.',

    'alpha_diversity_description_1' => 'The figure shows boxplots of alpha diversity displaying the distribution of microbial diversity within individual samples across different groups or conditions. The plot shows key statistical measures: the central line represents the median diversity value, while the box boundaries indicate the first and third quartiles (25th and 75th percentiles). The whiskers extend to show the range of typical values, and any points beyond the whiskers represent outliers with unusually high or low diversity.',
    'alpha_diversity_description_2' => 'By comparing boxplots across different groups, you can identify patterns in microbial diversity. Groups with higher median values have greater average diversity, while the height of each box indicates the variability within that group. Overlapping boxes suggest similar diversity levels between groups, whereas non-overlapping boxes may indicate significant differences in microbial community richness and evenness.',

    'beta_diversity_description_1' => 'The figure shows a Principal Coordinate Analysis (PCoA) plot of beta diversity. It visualizes the differences in microbial community composition between samples. Each point on the plot represents a single sample, and the distance between points reflects how similar or different the microbial communities are. Samples that cluster together (appear close to each other) have similar microbial compositions, while samples that are far apart have very different community structures.',
    'beta_diversity_description_2' => 'The plot displays the data in two dimensions, with each axis showing the percentage of variation explained by that particular coordinate. When samples group into distinct clusters, this often indicates that they share similar environmental conditions, treatments, or other factors that influence microbial community assembly. The percentage values on each axis help you understand how much of the total variation in your dataset is captured by the visualization &mdash; higher percentages indicate that more of the community differences are represented in the plot.',

    'diff_abundance_top_significant_description' => 'The plot shows the top :n bacteria in order of statistical significance &mdash; from most significant to least significant &mdash; that display abundance changes between :condition1 and :condition2. The length of each bar is proportional to the magnitude of the observed change. The color indicates the type of change. A red bar represents bacteria with higher abundance in :condition1 compared to :condition2. A blue bar represents bacteria with reduced abundance in :condition1 compared to :condition2. Next to each bar, symbols that encode statistical significance may be present: *** very high significance, ** high significance, * medium significance, . low significance.',
    'diff_abundance_top_fold_change_description' => 'The plot shows the top :n bacteria in order of abundance change &mdash; from most changed to least changed &mdash; between :condition1 and :condition2. The length of each bar is proportional to the magnitude of the observed change. The color indicates the type of change. A red bar represents bacteria with higher abundance in :condition1 compared to :condition2. A blue bar represents bacteria with reduced abundance in :condition1 compared to :condition2. Next to each bar, symbols that encode statistical significance may be present: *** very high significance, ** high significance, * medium significance, . low significance.',
    'diff_abundance_top_frequent_description' => 'The plot shows the top :n bacteria in order of frequency &mdash; from most frequent to least frequent &mdash; that display abundance changes between :condition1 and :condition2. The length of each bar is proportional to the magnitude of the observed change. The color indicates the type of change. A red bar represents bacteria with higher abundance in :condition1 compared to :condition2. A blue bar represents bacteria with reduced abundance in :condition1 compared to :condition2. Next to each bar, symbols that encode statistical significance may be present: *** very high significance, ** high significance, * medium significance, . low significance.',

    'functional_top_significant_description' => 'The plot shows the top :n features in order of statistical significance &mdash; from most significant to least significant &mdash; that display abundance changes between :condition1 and :condition2. The length of each bar is proportional to the magnitude of the observed change. The color indicates the type of change. A red bar represents features with higher abundance in :condition1 compared to :condition2. A blue bar represents features with reduced abundance in :condition1 compared to :condition2. Next to each bar, symbols that encode statistical significance may be present: *** very high significance, ** high significance, * medium significance, . low significance.',
    'functional_top_fold_change_description' => 'The plot shows the top :n features in order of abundance change &mdash; from most changed to least changed &mdash; between :condition1 and :condition2. The length of each bar is proportional to the magnitude of the observed change. The color indicates the type of change. A red bar represents features with higher abundance in :condition1 compared to :condition2. A blue bar represents features with reduced abundance in :condition1 compared to :condition2. Next to each bar, symbols that encode statistical significance may be present: *** very high significance, ** high significance, * medium significance, . low significance.',
    'functional_top_frequent_description' => 'The plot shows the top :n features in order of frequency &mdash; from most frequent to least frequent &mdash; that display abundance changes between :condition1 and :condition2. The length of each bar is proportional to the magnitude of the observed change. The color indicates the type of change. A red bar represents features with higher abundance in :condition1 compared to :condition2. A blue bar represents features with reduced abundance in :condition1 compared to :condition2. Next to each bar, symbols that encode statistical significance may be present: *** very high significance, ** high significance, * medium significance, . low significance.',

];
